### ISSUE TITLE
tsconfig issue

### ISSUE THREAD

**Issue by joshua1** [hmmhmmhm/svelte-template#1]
Hi @hmmhmmhm ,
With module set to "commonjs" in your tsconfig, try importing (using es6 import) a ts file into index.svelte . it fails with module not found. now when you set module to es6 or esnext, it works , but throws a build /start/ error (well when you run any of the npm scripts other than clean). 
with module set to es6 you get 
```
import { __assign, __awaiter, __generator } from "tslib";
       ^

SyntaxError: Unexpected token {
```
on build

**Comment by hmmhmmhm** [comment]
Hello! Could you give me module source code or give some name of the module that you're having trouble importing?

**Comment by joshua1** [comment]
you can check this repo. its a clone of this template with some import into index.svelte https://github.com/joshua1/st.git 
when you run ```yarn build ``` you get the  below error 
```

⠼ Building index.svelte...index.svelte:6:80 - error TS2307: Cannot find module './utils'.

6   import { registerServiceWorker, handleNetworkStatus, appDeviceInstall } from './utils'
                                                                                 ~~~~~~~~~

⠏ Building tslib.es6.js...index.svelte:6:80 - error TS2307: Cannot find module './utils'.

6   import { registerServiceWorker, handleNetworkStatus, appDeviceInstall } from './utils'
                                                                                 ~~~~~~~~~
```

**Comment by hmmhmmhm** [comment]
i'll check!

**Comment by joshua1** [comment]
if i switch moodule in tsconfig to *esnext* , i get the below error 
```
/Users/joshuao/Documents/Dev/starters/st/config/parcel.config.ts:1
import { __assign, __awaiter, __generator } from "tslib";
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Module.m._compile (/Users/joshuao/Documents/Dev/starters/st/node_modules/ts-node/src/index.ts:536:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/joshuao/Documents/Dev/starters/st/node_modules/ts-node/src/index.ts:539:12)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at main (/Users/joshuao/Documents/Dev/starters/st/node_modules/ts-node/src/bin.ts:212:14)
    at Object.<anonymous> (/Users/joshuao/Documents/Dev/starters/st/node_modules/ts-node/src/bin.ts:470:3)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
import in index.svelte works but the parcel.config.ts fails

**Comment by joshua1** [comment]
@hmmhmmhm  i think my issue is with default export in the index.ts file in my example. i just updated to named exports and its fine. no need to investigate on your part. Thanks for the quick response too

**Comment by hmmhmmhm** [comment]
I was gonna see after work, but it's already solved! congratulation!
